import { ArrowUpRight, CheckCircle2 } from 'lucide-react';
import Image from 'next/image';
import Link from 'next/link';

import manifestJson from '@/public/generated/guideshot/manifest.json';

import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';

interface GeneratedVariant {
  readonly alt: string;
  readonly height: number;
  readonly src: string;
  readonly width: number;
}

interface GeneratedEntry {
  readonly id: string;
  readonly title?: string;
  readonly variants: Readonly<Record<string, GeneratedVariant>>;
}

const manifest = manifestJson as {
  readonly entries: readonly GeneratedEntry[];
};

const featured = [
  {
    id: 'pilot.recipes.create',
    variantKey: 'locale=da;theme=dark',
    eyebrow: 'Authenticated · DA · dark',
  },
  {
    id: 'pilot.sign-in.email',
    variantKey: 'locale=en;theme=light',
    eyebrow: 'Unauthenticated · EN · light',
  },
] as const;

function publicSource(source: string): string {
  return `/generated/guideshot/${source.replace(/^\.\//, '')}`;
}

export function GeneratedShowcase() {
  const shots = featured.map(({ id, variantKey, eyebrow }) => {
    const entry = manifest.entries.find((candidate) => candidate.id === id);
    const variant = entry?.variants[variantKey];

    if (entry === undefined || variant === undefined) {
      throw new Error(
        `Missing generated showcase variant ${id}::${variantKey}.`,
      );
    }

    return { entry, eyebrow, variant };
  });

  const assetCount = manifest.entries.reduce(
    (count, entry) => count + Object.keys(entry.variants).length,
    0,
  );

  return (
    <section className="border-y border-border bg-card/45 py-24 sm:py-32">
      <div className="mx-auto max-w-7xl px-5 sm:px-8">
        <div className="mb-12 flex flex-col justify-between gap-6 sm:flex-row sm:items-end">
          <div className="max-w-2xl">
            <Badge variant="primary">Generated by GuideShot</Badge>
            <h2 className="mt-5 text-balance text-4xl font-semibold tracking-[-0.055em] sm:text-5xl">
              The pilot is its own proof.
            </h2>
            <p className="mt-5 leading-7 text-muted-foreground">
              These are committed outputs from the same recipes, scenarios, and
              capture pipeline documented here.
            </p>
          </div>
          <div className="flex items-center gap-2 text-sm font-semibold text-emerald-700">
            <CheckCircle2 className="size-4" />
            {assetCount} manifest assets verified
          </div>
        </div>

        <div className="grid gap-5 lg:grid-cols-2">
          {shots.map(({ entry, eyebrow, variant }) => (
            <Card
              className="overflow-hidden bg-background p-0 shadow-none"
              key={entry.id}
            >
              <CardContent className="bg-muted/45 p-2 sm:p-3">
                <Image
                  alt={variant.alt}
                  className="h-auto w-full rounded-xl border border-border"
                  height={variant.height}
                  src={publicSource(variant.src)}
                  width={variant.width}
                />
              </CardContent>
              <CardHeader className="border-t border-border">
                <p className="text-[10px] font-bold uppercase tracking-[0.14em] text-primary">
                  {eyebrow}
                </p>
                <CardTitle className="text-xl">
                  {entry.title ?? entry.id}
                </CardTitle>
                <CardDescription>
                  <code className="text-[11px]">{entry.id}</code>
                </CardDescription>
              </CardHeader>
            </Card>
          ))}
        </div>

        <div className="mt-8 flex flex-col gap-3 sm:flex-row">
          <Button asChild variant="outline">
            <Link href="/generated/guideshot/manifest.json">
              Open public manifest
              <ArrowUpRight className="size-4" />
            </Link>
          </Button>
          <Button asChild variant="ghost">
            <Link href="/demo">Reproduce the states</Link>
          </Button>
        </div>
      </div>
    </section>
  );
}
